### ISSUE TITLE
Flutter 3 compatibility

### ISSUE THREAD

**Issue by JanRegent** [JulyWitch/animated_snack_bar#1]
/C:/Android/flutter/.pub-cache/hosted/pub.dartlang.org/animated_snack_bar-0.2.1/lib/src/animated_snack_bar.dart:114:20: Warning: Operand of null-aware operation '!' has type
'WidgetsBinding' which excludes null.
 - 'WidgetsBinding' is from 'package:flutter/src/widgets/binding.dart'
 ('/C:/Android/flutter/packages/flutter/lib/src/widgets/binding.dart').
    WidgetsBinding.instance!.addPostFrameCallback(

**Comment by rockclaver** [comment]
Are we getting a fix for this anytime soon? @JulyWitch

**Comment by farhantandia** [comment]
just delete "!" inside 
`WidgetsBinding.instance!.addPostFrameCallback(` -> `WidgetsBinding.instance.addPostFrameCallback(`

**Comment by rockclaver** [comment]
@JulyWitch that is in your library isn't it best if you make that change and update the package? I don't think it's a good idea to update your package code.

**Comment by farhantandia** [comment]
I think its okay only for warning issue @Limitless-Kode

**Comment by rockclaver** [comment]
@JanRegent would you mind if I create a pull request to fix the warning? And maybe collaborate with you to add more features to it. Allowing users to change the snackbar colors, icons and border-radius would make this package the best on pub.dev.

**Comment by JulyWitch** [comment]
> @JanRegent would you mind if I create a pull request to fix the warning? And maybe collaborate with you to add more features to it. Allowing users to change the snackbar colors, icons and border-radius would make this package the best on pub.dev.

Sorry for my late reply, Feel free to raise pull requests

**Comment by JulyWitch** [comment]
@Limitless-Kode I have merged your PR and updated the package (v0.2.2), I will close this issue
