### ISSUE TITLE
some way to managing the top distance

### ISSUE THREAD

**Issue by pmella16** [JulyWitch/animated_snack_bar#12]
hi, is it possible to handle the top margin ??

![image](https://user-images.githubusercontent.com/19208317/235235836-95f7863f-bef9-4e01-b6e0-02629667fce9.png)

**Comment by JulyWitch** [comment]
Hi, Yeah It's actually on the master branch and available for `AnimatedSnackBar` default constructor.

I'll add it to other constructors and release it.

**Comment by JulyWitch** [comment]
Update it to `0.3.1` then you can use the `mobilePositionSettings` property:

```dart
AnimatedSnackBar.material(
    'This a snackbar with info type',
    type: AnimatedSnackBarType.info,
    mobilePositionSettings: const MobilePositionSettings(
      topOnAppearance: 100,
      // topOnDissapear: 50,
      // bottomOnAppearance: 100,
      // bottomOnDissapear: 50,
      // left: 20,
      // right: 70,
    ),
).show(context);
```
