### ISSUE TITLE
clean snack bar

### ISSUE THREAD

**Issue by pmella16** [JulyWitch/animated_snack_bar#13]
Hi, i need clean the navbar when i navigate to other page, i add this class to animated_snack_bar.dart
`class ClearAll {
  clean() {

    final index = _snackBars.indexWhere(
      (element) => element.info.key.currentContext != null,
    );

     if (index != -1) {

      _snackBars.removeWhere();
     }

  }
}
`

and work fine, i call the method ClearAll().clean(); when i am in the new page, but i think you can made this better

**Comment by JulyWitch** [comment]
Thank you for your suggestion, I'll add such a behavior in the next release

**Comment by JulyWitch** [comment]
Dear @pmella16 
I've added a new functionality in `v0.4.0` That you can use to manually remove all snack bars

```
AnimatedSnackBar.removeAll();
```

Please open a new issue if you notice any weird behavior
Thanks
