### ISSUE TITLE
Remove the SnackBar manually

### ISSUE THREAD

**Issue by kh-abir** [JulyWitch/animated_snack_bar#14]
I was building a custom-type AnimatedSnacKBar. How can I remove the snack bar manually onTap?

**Comment by Haris2v** [comment]
Yeah, I'm also looking for same functionality. Manual snackBar functionality is really needed in many cases

**Comment by JulyWitch** [comment]
Hello, Sorry for the late reply, I'll add this functionality in the next release

**Comment by JulyWitch** [comment]
Dear @kh-abir and @Haris2v 
This functionality is added in v0.4.0, Please open a new issue if you notice any weird behavior.

Here is an snippet of how you can delete a snack bar manually
```
final snackbar = AnimatedSnackBar(
    builder: ((context) {
        return Container(
            padding: const EdgeInsets.all(8),
            height: 50,
            child: const Text('A custom snackbar'),
        );
    }),
);
snackbar.show(context);

snackbar.remove()
```
