### ISSUE TITLE
AnimatedSnackBar is rendered behind the keyboard

### ISSUE THREAD

**Issue by quoc-huynh-cosee** [JulyWitch/animated_snack_bar#17]
If the keyboard is open while I show an AnimatedSnackBar, the AnimatedSnackBar is rendered behind the keyboard. With the normal SnackBar it is rendered above the keyboard.

**Comment by JulyWitch** [comment]
Thank you for opening an issue, I'll fix it in the next release

**Comment by JulyWitch** [comment]
Dear @quoc-huynh-cosee 
This issue is fixed in `v0.4.0`, Please open a new issue if you notice any weird behavior.

Thanks
