### ISSUE TITLE
Snackbar stacked by other snackbar

### ISSUE THREAD

**Issue by farhantandia** [JulyWitch/animated_snack_bar#2]
This condition happened if we click a button or there is another process that pop up this animated snackbar, if the duration is still on then it will not go off the screen, thus it will be stacked with another snackbar which is not really good in terms of UX, is there any function to immediately close the current animated snackbar so it will pop up consecutively for the next snackbar?
![Screenshot 2022-07-20 190416](https://user-images.githubusercontent.com/17233457/179967214-108036a1-0057-4470-a720-38724f760927.png)

**Comment by JulyWitch** [comment]
I didn't create such functionality 
I will fix this whenever I get time to work on it

**Comment by JulyWitch** [comment]
I have fix it in #5 (ver: 0.3.0)
You can pass `RemoveSnackBarStrategy` to `snackBarStrategy` prop to achieve this
