### ISSUE TITLE
Fail when sidebar menu is used

### ISSUE THREAD

**Issue by juanmigrau** [JulyWitch/animated_snack_bar#6]
Hi!
Our app includes some screens containing a sidebar menu (manually added, not from scaffold), and a view with its own navigator overlay. In these cases, the coordinates for the animatedPositioned are calculated taken into account the whole screen, but they are applied only to the view, causing the snackbar to be reduced.
I don't know if it is possible to solve the problem, or an optional parameter like 'offset' or similar would be convenient.

**Comment by JulyWitch** [comment]
Hi
Can you share some screenshots of it?
Thank you for reporting this issue

**Comment by JulyWitch** [comment]
I'm closing this due to not adding enough information about the issue.
