### ISSUE TITLE
Incorrect delay in short time

### ISSUE THREAD

**Issue by Tantrax007** [JulyWitch/animated_snack_bar#7]
Hello! 

Im using this package for my TFG and i see some problem with the intro and outro animation when the duration of the snackbar is short.
I mean, when I want to display for a second or less, the outro didn't appear, it pop's out without slide up. It's not a seriouse problem but I open an issue only for bring some feedback.

**Comment by JulyWitch** [comment]
Thank you for opening the issue and sorry for my late response, I'll fix this in the future releases

**Comment by JulyWitch** [comment]
Dear @Tantrax007 
This issue is fixed in `v0.4.0`
Please open a new issue if you noticed any weird behavior
