### ISSUE TITLE
Don't show repeated snack bars

### ISSUE THREAD

**Issue by Djihanegh** [JulyWitch/animated_snack_bar#8]
Hello,

is it possible to avoid showing similar snack bars coming one after the other ? this happens when the user tap on a button twice, I mean if a snack bar with the same text and type is still showing, and the another similar one is in the stack , I don't want to show the second one.

Thank you.

**Comment by JulyWitch** [comment]
Hey Djihanegh,

This problem should be solved in your app code and I don't think of it as this library's responsibility.
I'm closing this issue. Please reopen it if you think I've got it wrong or if you have something else in your mind.

Also to solve your issue, You have to add a timer in that button and not calling snack bar showing function until the time for previous one is finished.
